version: '3.8'

services:
  postgres:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oludotun
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  backend:
    container_name: backend
    build:
      context: ./backend/book_rental
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=oludotun
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./backend/book_rental/:/app
      - ./backend/book_rental/.env.docker:/app/.env
      - ./backend/book_rental/logs:/app/logs
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    container_name: web
    build:
      context: ./frontend/book_rental
    volumes:
      - ./frontend/book_rental:/app
      - ./frontend/book_rental/.env.example:/app/.env
    depends_on:
      - backend
    ports:
      - "8080:8080"

volumes:
  pgdata:
  media:
  static: